import { render, screen } from "@testing-library/react";
import Index from "../../pages/[[...slug]]/index";
import "@testing-library/jest-dom";

(global as any).fetch = jest.fn(() =>
  Promise.resolve({
    json: () =>
      Promise.resolve([
        {
          created_at: 0,
          components: ["build", "cli", "server"],
          types: ["performance-fix", "bug-fix", "feature"],
          short_descriptions: [
            "performance-fix: This is a short description of the build change",
            "performance-fix: This is a short description of the cli change",
            "bug-fix: This is a short description of the server change",
            "bug-fix: This is a short description of the build change",
            "feature: This is a short description of the build change",
          ],
          long_descriptions: [
            "## Random build feature\n\n ### Subheading build-performance-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random cli feature\n\n ### Subheading cli-performance-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random server feature\n\n ### Subheading server-bug-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random build feature\n\n ### Subheading build-bug-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random build feature\n\n ### Subheading build-feature\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
          ],
          markdown: "## Changelog\n\nThis is a changelog for this release",
          version: "v0.0.0",
          product: "cloud",
        },
        {
          created_at: 0,
          components: ["server", "cli", "build", "console"],
          types: ["performance-fix", "bug-fix", "feature"],
          short_descriptions: [
            "performance-fix: This is a short description of the server change",
            "bug-fix: This is a short description of the cli change",
            "bug-fix: This is a short description of the build change",
            "feature: This is a short description of the console change",
            "performance-fix: This is a short description of the cli change",
          ],
          long_descriptions: [
            "## Random server feature\n\n ### Subheading server-performance-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random cli feature\n\n ### Subheading cli-bug-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random build feature\n\n ### Subheading build-bug-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random console feature\n\n ### Subheading console-feature\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random cli feature\n\n ### Subheading cli-performance-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
          ],
          markdown: "## Changelog\n\nThis is a changelog for this release",
          version: "v0.0.1",
          product: "cloud",
        },
        {
          created_at: 0,
          components: ["console", "build"],
          types: ["performance-fix", "bug-fix", "feature"],
          short_descriptions: [
            "performance-fix: This is a short description of the console change",
            "performance-fix: This is a short description of the console change",
            "bug-fix: This is a short description of the build change",
            "feature: This is a short description of the build change",
            "bug-fix: This is a short description of the build change",
          ],
          long_descriptions: [
            "## Random console feature\n\n ### Subheading console-performance-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random console feature\n\n ### Subheading console-performance-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random build feature\n\n ### Subheading build-bug-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random build feature\n\n ### Subheading build-feature\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random build feature\n\n ### Subheading build-bug-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
          ],
          markdown: "## Changelog\n\nThis is a changelog for this release",
          version: "v0.1.0",
          product: "cloud",
        },
        {
          created_at: 0,
          components: ["console"],
          types: ["performance-fix", "feature"],
          short_descriptions: [
            "performance-fix: This is a short description of the console change",
            "feature: This is a short description of the console change",
          ],
          long_descriptions: [
            "## Random console feature\n\n ### Subheading console-performance-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random console feature\n\n ### Subheading console-feature\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
          ],
          markdown: "## Changelog\n\nThis is a changelog for this release",
          version: "v0.1.1",
          product: "cloud",
        },
        {
          created_at: 0,
          components: ["console", "build", "cli", "server"],
          types: ["bug-fix", "performance-fix", "feature"],
          short_descriptions: [
            "bug-fix: This is a short description of the console change",
            "performance-fix: This is a short description of the build change",
            "feature: This is a short description of the build change",
            "performance-fix: This is a short description of the console change",
            "performance-fix: This is a short description of the console change",
            "feature: This is a short description of the cli change",
            "performance-fix: This is a short description of the cli change",
            "bug-fix: This is a short description of the server change",
          ],
          long_descriptions: [
            "## Random console feature\n\n ### Subheading console-bug-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random build feature\n\n ### Subheading build-performance-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random build feature\n\n ### Subheading build-feature\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random console feature\n\n ### Subheading console-performance-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random console feature\n\n ### Subheading console-performance-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random cli feature\n\n ### Subheading cli-feature\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random cli feature\n\n ### Subheading cli-performance-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random server feature\n\n ### Subheading server-bug-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
          ],
          markdown: "## Changelog\n\nThis is a changelog for this release",
          version: "v1.0.0",
          product: "cloud",
        },
        {
          created_at: 0,
          components: ["build", "console", "server"],
          types: ["bug-fix", "feature", "performance-fix"],
          short_descriptions: [
            "bug-fix: This is a short description of the build change",
            "feature: This is a short description of the console change",
            "bug-fix: This is a short description of the build change",
            "feature: This is a short description of the server change",
            "performance-fix: This is a short description of the console change",
            "performance-fix: This is a short description of the build change",
            "performance-fix: This is a short description of the server change",
            "bug-fix: This is a short description of the build change",
            "feature: This is a short description of the server change",
          ],
          long_descriptions: [
            "## Random build feature\n\n ### Subheading build-bug-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random console feature\n\n ### Subheading console-feature\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random build feature\n\n ### Subheading build-bug-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random server feature\n\n ### Subheading server-feature\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random console feature\n\n ### Subheading console-performance-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random build feature\n\n ### Subheading build-performance-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random server feature\n\n ### Subheading server-performance-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random build feature\n\n ### Subheading build-bug-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random server feature\n\n ### Subheading server-feature\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
          ],
          markdown: "## Changelog\n\nThis is a changelog for this release",
          version: "v1.0.1",
          product: "cloud",
        },
        {
          created_at: 0,
          components: ["build"],
          types: ["bug-fix"],
          short_descriptions: [
            "bug-fix: This is a short description of the build change",
          ],
          long_descriptions: [
            "## Random build feature\n\n ### Subheading build-bug-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
          ],
          markdown: "## Changelog\n\nThis is a changelog for this release",
          version: "v1.1.0",
          product: "cloud",
        },
        {
          created_at: 0,
          components: ["console", "build", "cli"],
          types: ["feature", "performance-fix"],
          short_descriptions: [
            "feature: This is a short description of the console change",
            "performance-fix: This is a short description of the build change",
            "performance-fix: This is a short description of the build change",
            "performance-fix: This is a short description of the cli change",
          ],
          long_descriptions: [
            "## Random console feature\n\n ### Subheading console-feature\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random build feature\n\n ### Subheading build-performance-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random build feature\n\n ### Subheading build-performance-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
            "## Random cli feature\n\n ### Subheading cli-performance-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
          ],
          markdown: "## Changelog\n\nThis is a changelog for this release",
          version: "v1.1.1",
          product: "cloud",
        },
        {
          created_at: 1658982533294,
          components: ["cli"],
          types: ["bug-fix"],
          short_descriptions: [
            "bug-fix: This is a short description of the cli change",
          ],
          long_descriptions: [
            "## Random cli feature\n\n ### Subheading cli-bug-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
          ],
          version: "v0.0.0",
          markdown: null,
          product: "cloud",
        },
        {
          created_at: 1658981846531,
          components: ["console"],
          types: ["bug-fix"],
          short_descriptions: [
            "bug-fix: This is a short description of the console change",
          ],
          long_descriptions: [
            "## Random console feature\n\n ### Subheading console-bug-fix\n\nThis is a long description of the change\n.This is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\nThis is a long description of the change\n",
          ],
          version: "v0.0.0",
          markdown: null,
          product: "cloud",
        },
      ]),
  })
);

jest.mock("next/router", () => require("next-router-mock"));

describe("Index page", () => {
  it("renders hello world", async () => {
    render(<Index />);

    await screen.findByText("The Changelog");

    const heading = screen.getByText("The Changelog");

    expect(heading).toBeInTheDocument();
  });
});
